-- Tabla de clientes
create table clientes (
    id_cliente     number generated by default on null as identity primary key,
    nombre         varchar2(100),
    telefono       varchar2(20),
    email          varchar2(100),
    activo         varchar2(1) default 'S' check (activo in ('S', 'N'))
);

-- Tabla de plantillas
create table plantilla_mensajes (
    id_plantilla     number generated by default on null as identity primary key,
    nombre           varchar2(100),
    cuerpo_mensaje   clob,
    fecha_creacion   date default sysdate
);

-- Tabla de envíos de mensajes
create table envio_mensajes (
    id_envio         number generated by default on null as identity primary key,
    id_cliente       number references clientes(id_cliente),
    id_plantilla     number references plantilla_mensajes(id_plantilla),
    mensaje_enviado  clob,
    estado_envio     varchar2(20),
    fecha_envio      timestamp default current_timestamp,
    respuesta_api    clob
);
